from __future__ import annotations

from pathlib import Path


def build_dev_runtime_env_text(get_config):
    keys = (
        ('APP_DEV_MODE', 'dev_mode', 'false'),
        ('APP_DEV_AUTO_PULL', 'dev_auto_pull', 'false'),
        ('APP_DEV_GIT_REPO', 'dev_git_repo', ''),
        ('APP_DEV_GIT_BRANCH', 'dev_git_branch', 'master'),
        ('APP_DEV_AUTO_PIP_SYNC', 'dev_auto_pip_sync', 'true'),
        ('APP_DEV_PIP_SYNC_TIMEOUT', 'dev_pip_sync_timeout', '120'),
        ('APP_DEV_GIT_TOKEN', 'dev_git_token', ''),
        ('APP_DEV_PROXY_URL', 'dev_proxy_url', ''),
        ('APP_DEV_NO_PROXY', 'dev_no_proxy', 'localhost,127.0.0.1,::1'),
    )
    lines = ['# Auto-generated by HLM settings page. Applied on container restart.']
    for env_key, cfg_key, default in keys:
        val = str(get_config(cfg_key, default) or default)
        escaped = val.replace("'", "'\"'\"'")
        lines.append(f"{env_key}='{escaped}'")
    return '\n'.join(lines) + '\n'


def write_dev_runtime_env(get_config, runtime_file: str | Path):
    runtime_path = Path(runtime_file)
    runtime_path.parent.mkdir(parents=True, exist_ok=True)
    runtime_path.write_text(build_dev_runtime_env_text(get_config), encoding='utf-8')
    return runtime_path
